#!/bin/bash

s=`sensors -u | grep temp1_input | head -1 | cut -c 15-17`

# echo $s

if [ $s -gt "64" ]
then
    i8kfan - 2 > /dev/null
    echo FULL
elif [ $s -gt "49" ]
then
    i8kfan - 1 > /dev/null
    echo HALF
else
    i8kfan - 0 > /dev/null
    echo OFF
fi

