#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

# The second parameter overrides the mixer selection
# For PulseAudio users, use "pulse"
# For Jack/Jack2 users, use "jackplug"
# For ALSA users, you may use "default" for your primary card
# or you may use hw:# where # is the number of the card desired

STEP="${1:-5%}"
SINK=2 #this should be the Avantree Audition headset

#------------------------------------------------------------------------

volume() {
  pactl list sinks | grep '^[[:space:]]Volume:' | head -n  $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*%\).*,\1,'
}

isMuted() {
    muted=$(pactl list sinks | grep '^[[:space:]]Mute:' | tail -n 1 | cut -c 8-)

    if [ $muted = "yes" ];
    then
        echo MUTE
    fi
}

#------------------------------------------------------------------------


case $BLOCK_BUTTON in
  3) pactl set-sink-mute $SINK toggle ;;  # right click, mute/unmute
  4) pactl set-sink-mute $SINK false ; pactl set-sink-volume $SINK +${STEP};; # scroll up, increase
  5) pactl set-sink-mute $SINK false ; pactl set-sink-volume $SINK -${STEP};; # scroll down, decrease
esac

isMuted
volume
