#!/bin/bash

op=$1
step=7

if [[ ${op} != "+" ]] && [[ ${op} != "-" ]]; then
	echo "Usage: $0 [+,-]."
	exit 1
fi

current_brightness=$(cat /sys/class/backlight/intel_backlight/actual_brightness)
max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)

if [[ -z ${max_brightness} ]]; then
	echo "Could not detect maximum brightness."
	exit 1
fi

if [[ -z ${current_brightness} ]]; then
	echo "Could not detect current brightness."
	exit 1
fi

one_percent=$(echo "${max_brightness}/100" | bc)
new_brightness=$(echo "${current_brightness}${op}${step}*${one_percent}" | bc)


new_brightness=$(echo "define max(a, b) { 
	if (a > b) {
		return (a);
	} 
	return (b);
}
max(${new_brightness}, 100)" | bc)

new_brightness=$(echo "define min(a, b) { 
	if (a < b) {
		return (a);
	} 
	return (b);
}
min(${new_brightness}, ${max_brightness})" | bc)

echo "One percent means ${one_percent}."
echo "Old brightness: ${current_brightness}."
echo "New brightness: ${new_brightness}."

echo ${new_brightness} > /sys/class/backlight/intel_backlight/brightness
