#!/bin/bash
scale="1.75x1.75"

xrandr --output VIRTUAL1 --off \
       --output HDMI1 --off \
       --output eDP1 --off \
       --output DP2 --off \
       --output DP1-1 --off \
       --output DP1-2 --off \
       --output DP1 --mode 1920x1080 --pos 0x0 --rotate left --scale ${scale} \
       --output DP2-3 --mode 1920x1080 --pos 1890x1160 --rotate normal --scale ${scale}
