#!/bin/bash

t=`/usr/local/bin/temp | head -n 1`

if (( $(echo "$t > 60" | bc -l) )); then
    i8kfan - 2 > /dev/null
    echo 1
elif (( $(echo "$t > 49" | bc -l) )); then
    i8kfan - 1 > /dev/null
    # echo HALF
    echo ½
else
    i8kfan - 0 > /dev/null
    echo 0
fi
