#!/bin/bash

# Deactivates any external display and activates integrated display

xrandr --output VIRTUAL1 --off \
       --output HDMI1 --off \
       --output eDP1 --primary --mode 2560x1440 --pos 0x0 --rotate normal \
       --output DP1 --off \
       --output DP2 --off \
       --output DP1-1 --off \
       --output DP1-2 --off \
       --output DP1-3 --off \
       --output DP2-1 --off \
       --output DP2-2 --off \
       --output DP2-3 --off
