#!/bin/bash
set -e

if [[ -z $(which scrot) ]]; then
  echo "Scrot is required for taking screenshots."
fi


filename="$HOME/Pictures/$(date +"%Y-%m-%d-%H-%M-%S").png"
scrot -q 75 -s "${filename}"

echo "Saved screenshot to ${filename}"
xclip -selection clipboard -t image/png -i "${filename}"
